DROP TABLE IF EXISTS log_consulta;

CREATE TABLE log_consulta(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consulta_id INTEGER NOT NULL,
    medico_nome VARCHAR(100) NOT NULL,
    paciente_nome VARCHAR(100) NOT NULL,
    especialidade_nome VARCHAR(100) NOT NULL,
    data_consulta VARCHAR(10) NOT NULL,
    hora_consulta VARCHAR(5) NOT NULL
);

INSERT INTO log_consulta(consulta_id, medico_nome, paciente_nome, especialidade_nome, data_consulta, hora_consulta) VALUES
(1, 'Dr. Daniel Notari', 'Lucas Zorrer', 'Cardiologia', '22/04/2026', '09:00'),
(2, 'Dr. Alexandre Krohn', 'Gustavo Quadri', 'Pediatria', '22/04/2026', '10:30'),
(3, 'Dr. Andre Martinotto', 'Zezinho da Silva', 'Ortopedia', '22/04/2026', '14:00');
